"""ajout champs profil user (nom, prenom, entreprise)

Revision ID: 7239b9e48d12
Revises: 69dfd86650b6
Create Date: 2026-09-07 18:14:13.187544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7239b9e48d12'
down_revision: Union[str, Sequence[str], None] = '69dfd86650b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prenom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('entreprise', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('entreprise')
        batch_op.drop_column('prenom')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
